# Generated by Django 3.1 on 2020-09-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_sw7up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='specific_id',
            field=models.CharField(max_length=25),
        ),
    ]
