# Generated by Django 3.1 on 2020-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.CharField(default='공통', max_length=10),
        ),
    ]
