# Generated by Django 3.1 on 2020-08-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_sw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
    ]
