# Generated by Django 3.1 on 2020-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_sw', '0002_auto_20200830_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='specific_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
