# Generated by Django 3.1 on 2020-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_sw', '0003_post_specific_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
