# Generated by Django 3.1 on 2020-08-27 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0003_auto_20200826_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
