# Generated by Django 3.1 on 2020-09-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_question_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
