# Generated by Django 3.1 on 2020-09-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_answer_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='post',
        ),
    ]
