# Generated by Django 3.1 on 2020-08-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upload_files',
        ),
    ]
