# Generated by Django 3.1 on 2020-08-25 17:45

from django.db import migrations, models
import emsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('emsys', '0002_auto_20200826_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='question',
            name='upload_files',
            field=models.FileField(blank=True, null=True, verbose_name='파일'),
        ),
    ]
